### ISSUE TITLE
missing cert file

### ISSUE THREAD

**Issue by marc-2019** [reality-two/reality2-node-core-elixir#17]
When following the instruction below I couldn't find the cert file to copy.

"Again, in the folder above the Reality2 folder, create a folder called 'cert'. Either copy or link the Reality2/cert/generate_certificates file into this folder. Go into that folder in command line, and run the script. DO NOT RUN THAT SCRIPT INSIDE THE CERT FOLDER IN THE REALITY2 FOLDER, ONLY RUN IT IN THE CERT FOLDER YOU HAVE JUST CREATED. ALSO, DON'T SYMBOLICALLY LINK TO THE REALITY2/CERT FOLDER AS THAT WILL STILL LEAVE THE CERTIFICATES INSIDE THE REALITY2 FOLDER. Again, this is for security reasons."

**Comment by reality2-roycdavies** [comment]
This is no longer required.  The instructions have been modified accordingly.
