### ISSUE TITLE
after following upgrade instructions for 0.1.9 running gives the below error.

### ISSUE THREAD

**Issue by marc-2019** [reality-two/reality2-node-core-elixir#22]
marc@marc-H470-AORUS-PRO-AX:~/RootR2$ cd x86_64_GNU_Linux/
marc@marc-H470-AORUS-PRO-AX:~/RootR2/x86_64_GNU_Linux$ tar -zxf reality2_0.1.9.tar.gz
marc@marc-H470-AORUS-PRO-AX:~/RootR2/x86_64_GNU_Linux$ cd reality2
marc@marc-H470-AORUS-PRO-AX:~/RootR2/x86_64_GNU_Linux/reality2$ ./run
**************************************
Running: reality2 0.1.9
**************************************
/home/marc/RootR2/x86_64_GNU_Linux/reality2/erts-15.0/bin/erlexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /home/marc/RootR2/x86_64_GNU_Linux/reality2/erts-15.0/bin/erlexec)

**Comment by reality2-roycdavies** [comment]
Is this running in a docker container?  What version of the OS are you running?  This error occurs when the compiled version of Reality2 is using / has been compiled with a later version of libc than the OS or container is using.  It should work with a newer OS variant in the container.

**Comment by marc-2019** [comment]
Hi Roy, 

This is on ubuntu on the bare metal machine. Ubuntu 24.04.1 LTS

**Comment by reality2-roycdavies** [comment]
As far as I can find on the Internet, this seems to be related to the GLIBC installation.  I'm suspecting perhaps a mismatch between the version that is installed on the computer and the version that erlang/elixir was compiled with.  But there doesn't seem to be a solution aside from recompiling the source code with perhaps an older version of glibc.  I'm just about to put up version 0.1.10 (hopefully tonight), so it would be good to see if the problem persists.  I can't seem to reproduce the problem myself.

**Comment by marc-2019** [comment]
Thanks, we can close it off, I will nuke what I have and pull the files down again. Could be just the upgrade is an issue.

**Comment by marc-2019** [comment]
Resolved by removing previous version and installing new version, although did prompt an update to my elixir version.
